### ISSUE TITLE
Demo data and processes are not being registered

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-r-backend#18]
I downloaded the demo data and processes via `loadDemo()` and the download worked (I have both the landsat7 and sentinel2 folders). But it appears that the data and processes are not being registered -- the corresponding arrays returned by the `/collections` and `/processes` endpoints are empty.

Inspecting the `openeo.server` object in R revealed that `$data` and `$processes` are both empty lists of length 0...

I manually executed [`data.R`](https://github.com/Open-EO/openeo-r-backend/blob/9eb4fcace7dad5277641725f56a0bc47f2e48f99/R/data.R) and called the `loadSentinel2Data` and `loadLandsat7Dataset` functions. The first failed with an error:
> Fehler in if (nchar(fname) == 0) stop("empty file name") : Fehlender Wert, wo TRUE/FALSE nötig ist

The second worked, so I at least have one dataset in `data`, but this should work automatically (or be done with a `registerDemo()` function). And the `processes` are still completely empty...

**Comment by flahn** [comment]
I guess there is an issue with the data / workspace path. Can you check whether `openeo.server$data.path` points to the correct data folder? If you don't provide a specific `workspace.path`, then it will be the current working directory (getwd()). The data that is downloaded is usally stored in `workspace.path/data`.

Otherwise you might try and set a designated workspace.path that you use everytime you run the start script.

**Comment by christophfriedrich** [comment]
I never changed the working directory (always left out the third line of the readme's startup snippet)

`getwd()` returns `/home/christoph`.
`openeo.server$workspaces.path` returns `/home/christoph`, too.
`openeo.server$data.path` is set to `/home/christoph/data`
That folder exists and contains both the `sentinel2` and `landsat7` folders with lots of images and the .md and .csv files you mentioned in the other issue.
There is also a `openeo.sqlite` file in `/home/christoph`.

So I think everything is where it should be :thinking:

I want to be a good support seeking user so I tried as you said: I cleared everything once more, executed the startup script again and this time didn't leave out the workspace line: 
`openeo.server$workspaces.path = "/home/christoph/rbackend"`

Output after `loadDemo()`:
> Fehler in CRS(x) : no system list, errno: 2
Zusätzlich: Warnmeldung:
In dir.create(data.path, recursive = TRUE) :
  '/home/christoph/rbackend/data' existiert bereits

So the same error message as in the other issue...

**Comment by flahn** [comment]
If the problem is related to the CRS() function I would assume that there is a problem with the PROJ.4 installation of GDAL or at least with the GDAL or rgdal configuration. Might be a good idea to start from there.

**Comment by flahn** [comment]
look [here](http://r-sig-geo.2731867.n2.nabble.com/spTransform-error-Error-in-CRS-quot-init-EPSG-26920-quot-no-system-list-errno-2-td7587591.html) for reference. Apparently on OSX machines there is a huge problem with case sensitivity - meaning that epsg had to be all lower character instead all capital letters.
